name: Test workflow

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:


jobs:
  OutputToLog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          repository: actions/checkout
  
